export default {
    API_ENDPOINT: 'https://crmmia-api.herokuapp.com/api',
    LOGIN_ENDPOINT: 'https://crmmia-api.herokuapp.com/api/users',
    COMMENTS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/commtypes',
    PROMOTIONS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/promotions',
    MAINTENANCE_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/mainttypes',
    PROPERTY_FEATURE_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/featuretypes',
    PROPERTY_STATUS_ENDPOINT:'http://crmmia-api.herokuapp.com/api/statuses',
    CUSTOMER_STATUS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/cstatuses',
    REMINDERS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/remainders',
    CATEGORIES_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/categories',
    PROCESS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/processts',
    COMPANY_SETUP_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/companies/6',
    ASSET_TYPE_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/assettypes',
    CUSTOMER_ACCOUNTS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/customers',
    MAINTENANCE_PROVIDERS_ENDPOINT: 'https://crmmia-api.herokuapp.com/api/providers',
    ASSIGN_PROMOTIONS_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/assignedproms',
    BROKER_ENDPOINT: 'http://crmmia-api.herokuapp.com/api/brokers',
    API_KEY: process.env.REACT_APP_API_KEY,
    TOKEN_KEY: 'client-auth-token',
  }